Automated plotting
biosustain/Maud pull request #250
Opened 2020-10-12 08:35 UTC by NicholasCowie

# Summary
This is a tool to help plot your posterior draws. It's fairly basic at the moment and doesn't spit out the prettiest plots but is 99% automated only requiring the following inputs which are noted in the documentation:
* TOML file directory (relative to Maud home directory)
* CSV file directory (relative to Maud home directory)
* model name
* csv timestamp code

# Output Plots
The current output plots are:
* concentrations
* fluxes
* enzyme concentrations
* formation energies
* Keqs
* kcats
* Kms

# Commit History
* feat: automated plotting of population
* style: fixing black style guide
* Docs: update dependencies for plotting using plotnine

# Future Directions with Plotting
There are several features not implemented that will be once a finalised file structure is resolved:
* overlaying measured/prior values with CIs
* prettier plots in general

2020-10-12 09:44 UTC, NicholasCowie commented
Can someone try this on their computer?

2020-10-12 14:28 UTC, teddygroves requested changes
I think since `plot_samples.py` is a script it shouldn't go in the `src/maud` folder but either in the project root or in a separate `scripts` folder. 

Otherwise looks good!

2020-10-12 14:28 UTC, teddygroves commented on src/maud/plot_samples.py
> +run_number = "202010091734"  # number specific to each run
capitalise

2020-10-12 14:28 UTC, teddygroves commented on src/maud/plot_samples.py
> +    "RESULTS": os.path.join(
"data" and "results" should be lower case here I think

2020-10-13 13:32 UTC, teddygroves approved these changes

2020-10-13 13:33 UTC, merged